title: Riaz Virani
logo: img/profile.png
description: Institutional Intelligence Analyst | Optimizing Institutional Performance Through Data & Insight | Engaged, Adaptable, and Ready to Deliver
#show_downloads: true
theme: jekyll-theme-minimal
