title: Riaz Virani
logo: img/profile-pic.png
description: Data Alchemist | Bridging the Gap Between Data and Value | Microsoft Certified Data Engineer
show_downloads: true
theme: jekyll-theme-minimal
