title: Riaz Virani
#logo: /assets/img/headshot_circle.png
description: Data Alchemist | Bridging the Gap Between Data and Value | Microsoft Certified Data Engineer
show_downloads: true
theme: jekyll-theme-minimal
