title: Riaz Virani
logo: img/profile.png
description: Data Alchemist | Reimagining Healthcare | Bridging the Gap Between Data and Value | Cultural Chameleon: Adaptable, Engaged, and Ready to Thrive!
#show_downloads: true
theme: jekyll-theme-minimal
